# pre-commit configuration
# vim: set ts=2 sts=2 sw=2 et ci nu ft=yaml:
---
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle

  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]

  - repo: https://github.com/thibaudcolas/curlylint
    rev: "v0.13.1" # select a tag / sha to point at
    hooks:
      - id: curlylint
        files: \.j2

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        files: \.css$

  - repo: https://github.com/Lucas-C/pre-commit-hooks-lxml
    rev: v1.1.0
    hooks:
      - id: forbid-html-img-without-alt-text
      - id: forbid-non-std-html-attributes
      - id: detect-missing-css-classes
        args:
          - --css-files-dir
          - css
          - --html-files-dir
          - templates
      - id: html-tags-blacklist
      - id: html-attributes-blacklist

  - repo: https://github.com/pre-commit/mirrors-csslint
    rev: 'v1.0.5'  # Use the sha / tag you want to point at
    hooks:
      - id: csslint
        args:
          - --ignore=import
        files: \.css
