[tool.poetry]
name = "ukebook-md"
version = "1.0.1"
description = "tools to build songbooks from UDN files"
authors = ["Stuart Sears <stuart@sjsears.com>"]
license = "GPL-3-Or-Later"

[tool.poetry.dependencies]
python = "^3.10"
weasyprint = "^61.0"
ukedown = "^2.1.1"
lxml = "^5.1.1"
requests = "^2.28.2"
beautifulsoup4 = "^4.11.2"
PyYAML = "^6.0"
progress = "^1.6"
pip-tools = "^7.2.0"
jinja2 = "^3.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pre-commit = "^3.1.1"
ruff = "^0.3.4"
mypy = "^1.9.0"
types-pyyaml = "^6.0.12.20240311"
types-beautifulsoup4 = "^4.12.0.20240229"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
htmlbook = "ukebook_md.genbook:main"
pdfbook = "ukebook_md.makepdf:main"
pdfsong = "ukebook_md.makesong:main"


# generic python project config
[tool.pyright]
# configuration for the pyright syntax checker/linter
# handles warnings about variables for which we do not yet
# know the type
reportOptionalSubscript = false
reportOptionalIterable = false
reportOptionalMemberAccess = false
reportGeneralTypeIssues = false

[tool.black]
# project-specific black setup
line-length = 88
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '/(\.git|_build|build|dist|\.tox|\.venv)/'

[tool.isort]
# import-sorting plugin
profile = "black"
